name: Code Tree Analysis

on:
  pull_request:

jobs:
  code-tree-analysis:
    name: Code tree analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Get changed files
        id: files
        uses: Ana06/get-changed-files@v2.2.0

      - name: Perform code tree analysis
        id: code-tree-analysis
        continue-on-error: true
        run: |
          uv run python .github/workflows/scripts/code_tree_analysis.py "${{ steps.files.outputs.all }}"
